name: "Run Runtime Action Destroy"
description: "Runs Runtime Action Destroy with parameters"
inputs:
  FEATURES_LEVEL_LOG:
    description: "Log Level"
    required: true
  CLIENT_ID:
    description: "CLIENT ID"
    required: true
  CLIENT_KEY:
    description: "CLIENT KEY"
    required: true
  CLIENT_REALM:
    description: "CLIENT REALM"
    required: true 
  REPOSITORY_NAME:
    description: "Git Repository Name"
    required: true 
  AWS_ACCESS_KEY_ID:
    description: "AWS ACCESS KEY ID from console"
    required: true 
  AWS_SECRET_ACCESS_KEY:
    description: "AWS SECRET ACCESS KEY from console"
    required: true 
  AWS_SESSION_TOKEN:
    description: "AWS SESSION TOKEN from console"
    required: true 
  AWS_REGION:
    description: "AWS REGION"
    required: true 
  RUN_TASK_ID:
    description: "Runtime Run Task Id"
    required: true 

runs:
  using: "composite"
  steps:

    - name: Check Runner
      run: echo 🤖 OS runner is $(uname)
      shell: bash
      
    - name: Run Runtime Action Destroy
      run: |
        docker run --rm \
        -e FEATURES_LEVEL_LOG=${{ inputs.FEATURES_LEVEL_LOG }} \
        -e AUTHENTICATE_CLIENT_ID=${{ inputs.CLIENT_ID }} \
        -e AUTHENTICATE_CLIENT_SECRET=${{ inputs.CLIENT_KEY }} \
        -e AUTHENTICATE_CLIENT_REALMS=${{ inputs.CLIENT_REALM }} \
        -e AUTHENTICATE_URL="https://idm.stackspot.com" \
        -e REPOSITORY_NAME=${{ inputs.REPOSITORY_NAME }} \
        -e FEATURES_API_MANAGER="https://runtime-manager.v1.stackspot.com" \
        -e FEATURES_BASEPATH_TMP="/tmp/runtime/deploys" \
        -e FEATURES_BASEPATH_EBS="/opt/runtime" \
        -e FEATURES_BACKEND_FILEPATH="/app/" \
        -e FEATURES_BASEPATH_TERRAFORM="/root/.asdf/shims/terraform" \
        -e AWS_ACCESS_KEY_ID=${{ inputs.AWS_ACCESS_KEY_ID }} \
        -e AWS_SECRET_ACCESS_KEY=${{ inputs.AWS_SECRET_ACCESS_KEY }} \
        -e AWS_SESSION_TOKEN=${{ inputs.AWS_SESSION_TOKEN }} \
        -e AWS_REGION=${{ inputs.AWS_REGION }} \
        --entrypoint=/app/stackspot-runtime-job-destroy \
        stackspot/runtime-destroy start --run-task-id="${{ inputs.RUN_TASK_ID }}"
      shell: bash

branding:
    icon: 'terminal'
    color: 'orange'
